# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - kebab-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: kebab
  AZURE_WEBAPP_DIR: ./myExpressApp

jobs:
  job1:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1        
      with:
        node-version: '14.x'
    - name: npm install, build, and test
      run: |
        npm install ${{ env.AZURE_WEBAPP_DIR }}
        npm run build --if-present ${{ env.AZURE_WEBAPP_DIR }}
        npm run test --if-present ${{ env.AZURE_WEBAPP_DIR }}

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: .

  deploy:
    runs-on: windows-latest
    needs: job1
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kebab-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a4334362e96142a08c0be13244ac1061 }}
        package: .